version: '3'

services:
  scraper:
    build: ./cloud_function
    container_name: scraper
    platform: linux/amd64
    ports:
      - 8080:8080

  crypto_data:
    build: ./crypto_data_function
    container_name: crypto_data
    platform: linux/amd64
    ports:
      - 8080:8080
