version: '3'

services:
  scraper:
    build: ./cloud_function
    container_name: scraper
    platform: linux/amd64
    ports:
      - 8080:8080

  crypto_data:
    build: ./crypto_data_function
    container_name: crypto_data
    platform: linux/amd64
    ports:
      - 8080:8080

  marketstore:
    image: alpacamarkets/marketstore:v2.1.1
    container_name: marketstore
    platform: linux/amd64
    network_mode: host
    volumes:
      - $PWD/mktsdb:/project/data/mktsdb
      - $PWD/btc_history.yml:/tmp/mkts.yml
      - $PWD/btc_data:/data
    command: marketstore -config /tmp/mkts.yml
    ports:
      - 5993:5993

  predictor_api:
    build: ./predictor_api
    restart: always
    container_name: predictor_api
    ports:
      - 8080:8080

