version: 2.1

orbs:
  terraform: circleci/terraform@3.1.0
  python: circleci/python@2.0.3
  gcp-gcr: circleci/gcp-gcr@0.15.0

workflows:
  deploy_infrastructure:
    jobs:
      - build_push_image_social_media_scraper
      - build_push_image_crypto_data_scraper
      - terraform/fmt:
          checkout: true
          context: terraform
          requires:
            - build_push_image_social_media_scraper
            - build_push_image_crypto_data_scraper
      - terraform/validate:
          checkout: true
          context: terraform
          requires:
            - terraform/fmt
      - terraform/plan:
          checkout: true
          context: terraform
          persist-workspace: true
          requires:
            - terraform/validate
      - request-deploy:
          type: approval
          requires:
            - terraform/plan
      - terraform/apply:
          attach-workspace: true
          context: terraform
          requires:
            - request-deploy

  code-validation:
    jobs:
      - python-test

jobs:
  python-test:
    docker:
      - image: circleci/python:3.9.1
    steps:
      - checkout
      - run:
          name: Install Python Dependencies
          command: pip install -r cloud_function/requirements.txt && pip install ./cloud_function
      - run:
          name: Run tests
          command: export PYTHONPATH=$PYTHONPATH:/cloud_function && ./cloud_function/test.sh

  build_push_image_social_media_scraper:
    docker:
      - image: circleci/python:3.9.1
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Build social media scraper docker image
          command: ./cloud_function/build-image.sh
      - gcp-gcr/gcr-auth:
          gcloud-service-key: GOOGLE_CLOUD_KEYS
          google-project-id: GOOGLE_PROJECT_ID
          google-compute-zone: GOOGLE_COMPUTE_ZONE
      - gcp-gcr/push-image:
          google-project-id: GOOGLE_PROJECT_ID
          registry-url: "gcr.io"
          image: $IMAGE_NAME

  build_push_image_crypto_data_scraper:
    docker:
      - image: circleci/python:3.9.1
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build crypto data scraper docker image
          command: ./crypto_data_function/build-image.sh
      - gcp-gcr/gcr-auth:
          gcloud-service-key: GOOGLE_CLOUD_KEYS
          google-project-id: GOOGLE_PROJECT_ID
          google-compute-zone: GOOGLE_COMPUTE_ZONE
      - gcp-gcr/push-image:
          google-project-id: GOOGLE_PROJECT_ID
          registry-url: "gcr.io"
          image: $IMAGE_NAME
          tag: latest,$CIRCLE_SHA1
