version: 2.1

orbs:
  terraform: circleci/terraform@3.1.0
  python: circleci/python@2.0.3
  gcp-gcr: circleci/gcp-gcr@0.15.0

workflows:
  deploy_infrastructure:
    jobs:
      - build_push_image_social_media_scraper
      - build_push_image_crypto_data_scraper
      - build_push_image_predictor_api
      - terraform/fmt:
          checkout: true
          context: terraform
          requires:
            - build_push_image_social_media_scraper
            - build_push_image_crypto_data_scraper
            - build_push_image_predictor_api
      - terraform/validate:
          checkout: true
          context: terraform
          requires:
            - terraform/fmt
      - terraform/plan:
          checkout: true
          context: terraform
          persist-workspace: true
          requires:
            - terraform/validate
      - request-deploy:
          type: approval
          requires:
            - terraform/plan
      - terraform/apply:
          attach-workspace: true
          context: terraform
          requires:
            - request-deploy

  code-validation:
    jobs:
      - test-cloud-function
      - test-alpaca-data-function
      - test-predictor-api

jobs:
  test-cloud-function:
    docker:
      - image: cimg/python:3.9.1
    steps:
      - checkout
      - run:
          name: Install Python Dependencies
          command: pip install -r cloud_function/requirements.txt && pip install ./cloud_function
      - run:
          name: Run tests
          command: export PYTHONPATH=$PYTHONPATH:/cloud_function && ./cloud_function/test.sh

  test-alpaca-data-function:
    docker:
      - image: cimg/python:3.9.1
    steps:
      - checkout
      - run:
          name: Install Python Dependencies
          command: pip install -r alpaca_data_function/requirements.txt && pip install ./alpaca_data_function
      - run:
          name: Run tests
          command: export PYTHONPATH=$PYTHONPATH:/alpaca_data_function && ./alpaca_data_function/test.sh

  test-predictor-api:
    docker:
      - image: cimg/python:3.9.1
    steps:
      - checkout
      - run:
          name: Install Python Dependencies
          command: pip install -r predictor_api/requirements.txt && pip install ./predictor_api
      - run:
          name: Run tests
          command: export PYTHONPATH=$PYTHONPATH:/predictor_api && ./predictor_api/test.sh

  build_push_image_social_media_scraper:
    docker:
      - image: cimg/python:3.9.1
    executor: python/default
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Build social media scraper docker image
          command: ./cloud_function/build-image.sh
      - gcp-gcr/gcr-auth:
          gcloud-service-key: GOOGLE_CLOUD_KEYS
          google-project-id: GOOGLE_PROJECT_ID
          google-compute-zone: GOOGLE_COMPUTE_ZONE
      - gcp-gcr/push-image:
          google-project-id: GOOGLE_PROJECT_ID
          registry-url: "gcr.io"
          image: $IMAGE_NAME
          tag: latest,$CIRCLE_SHA1

  build_push_image_crypto_data_scraper:
    docker:
      - image: cimg/python:3.9.1
    executor: python/default
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Build crypto data scraper docker image
          command: ./alpaca_data_function/build-image.sh
      - gcp-gcr/gcr-auth:
          gcloud-service-key: GOOGLE_CLOUD_KEYS
          google-project-id: GOOGLE_PROJECT_ID
          google-compute-zone: GOOGLE_COMPUTE_ZONE
      - gcp-gcr/push-image:
          google-project-id: GOOGLE_PROJECT_ID
          registry-url: "gcr.io"
          image: $IMAGE_NAME
          tag: latest,$CIRCLE_SHA1

  build_push_image_predictor_api:
    docker:
      - image: cimg/python:3.9.1
    executor: python/default
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Build stock predictor API docker image
          command: ./predictor_api/build-image.sh
      - gcp-gcr/gcr-auth:
          gcloud-service-key: GOOGLE_CLOUD_KEYS
          google-project-id: GOOGLE_PROJECT_ID
          google-compute-zone: GOOGLE_COMPUTE_ZONE
      - gcp-gcr/push-image:
          google-project-id: GOOGLE_PROJECT_ID
          registry-url: "gcr.io"
          image: $IMAGE_NAME
          tag: latest,$CIRCLE_SHA1
